FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["ContaCorrenteMS/ContaCorrenteMS.csproj", "ContaCorrenteMS/"]
RUN dotnet restore "ContaCorrenteMS/ContaCorrenteMS.csproj"
COPY . .
WORKDIR "/src/ContaCorrenteMS"
RUN dotnet build "ContaCorrenteMS.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "ContaCorrenteMS.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "ContaCorrenteMS.dll"]